server:
  port: 9006
spring:
  redis:
    host: 192.168.163.1
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.163.1
     # database: spitdb
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
    instance:
      prefer-ip-address: true