
server:
  port: 9005
spring:
  application:
    name: tensquare-gathering #指定服务名
  datasource:
    url: jdbc:mysql://192.168.163.1:3306/tensquare_gathering?charactrEncoding=utf-8
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: 192.168.163.1
#jwt:
#   config:
#      key:
#        itcast
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
    instance:
      prefer-ip-address: true
debug: true
#feign:
#  hystrix:
#    enabled: true
